import type { Character } from "../types/character";
import type { ElementUpgradeMaterials } from "../types/elementUpgradeMaterials";
import type { CharacterUpgradeConfig } from "../types/upgradeConfig";

export const characters: Character[] = [
	{
		name: "Phoxhunter",
		rank: "B",
		id: 1,
		element: "Lumino",
		source: "Story",
		nocturnalEchoMaterial: "Ring of Escaped Entropy",
		skillUpgradeMaterials: {
			t1: "Herbal Sprig",
			t2: "Processed Herb",
			t3: "Compound Potion",
		},
		imagecode: "MC",
	},
	{
		name: "Margie",
		rank: "A",
		id: 2,
		element: "Pyro",
		source: "StoryShop - Trial Rank",
		nocturnalEchoMaterial: "Ring of Escaped Entropy",
		skillUpgradeMaterials: {
			t1: "Gleaming Arrow",
			t2: "Gleaming Precision Scope",
			t3: "Gleaming Quiver",
		},
		imagecode: "Maer",
	},
	{
		name: "Berenica",
		rank: "A",
		id: 3,
		element: "Umbro",
		source: "Pre-registration Reward",
		nocturnalEchoMaterial: "Ring of Severed Fear",
		skillUpgradeMaterials: {
			t1: "Iron Emblem",
			t2: "Silver Emblem",
			t3: "Gilded Emblem",
		},
		consonanceWeapon: "Sword",
		imagecode: "Heitao",
	},
	{
		name: "Outsider",
		rank: "A",
		id: 4,
		element: "Anemo",
		source: "StoryShop - Trial Rank",
		nocturnalEchoMaterial: "Ring of Escaped Entropy",
		skillUpgradeMaterials: {
			t1: "Gleaming Arrow",
			t2: "Gleaming Precision Scope",
			t3: "Gleaming Quiver",
		},
		imagecode: "Aote",
	},
	{
		name: "Randy",
		rank: "A",
		id: 5,
		element: "Electro",
		source: "Shop - Trial Rank 20",
		nocturnalEchoMaterial: "Ring of Severed Fear",
		skillUpgradeMaterials: {
			t1: "Iron Emblem",
			t2: "Silver Emblem",
			t3: "Gilded Emblem",
		},
		imagecode: "Landi",
	},
	{
		name: "Daphne",
		rank: "A",
		id: 6,
		element: "Anemo",
		source: "StoryShop - Trial Rank",
		nocturnalEchoMaterial: "Ring of Justice Rekindled",
		skillUpgradeMaterials: {
			t1: "Herbal Sprig",
			t2: "Processed Herb",
			t3: "Compound Potion",
		},
		imagecode: "Dafu",
	},
	{
		name: "Rebecca",
		rank: "B",
		id: 7,
		element: "Hydro",
		source: "StoryShop - Trial Rank",
		nocturnalEchoMaterial: "Ring of Escaped Entropy",
		skillUpgradeMaterials: {
			t1: "Veil of Silence",
			t2: "Eye of Infinity",
			t3: "Crown of Enlightenment",
		},
		imagecode: "Shuimu",
	},
	{
		name: "Lynn",
		rank: "B",
		id: 8,
		element: "Pyro",
		source: "Shop - Trial Rank 34",
		nocturnalEchoMaterial: "Ring of Severed Fear",
		skillUpgradeMaterials: {
			t1: "Gleaming Arrow",
			t2: "Gleaming Precision Scope",
			t3: "Gleaming Quiver",
		},
		consonanceWeapon: "Dual Pistols",
		imagecode: "Linen",
	},
	{
		name: "Sibylle",
		rank: "B",
		id: 9,
		element: "Electro",
		source: "Shop - Trial Rank 36",
		nocturnalEchoMaterial: "Ring of Severed Fear",
		skillUpgradeMaterials: {
			t1: "Veil of Silence",
			t2: "Eye of Infinity",
			t3: "Crown of Enlightenment",
		},
		imagecode: "Xibi",
	},
	{
		name: "Lady Nifle",
		rank: "B",
		id: 10,
		element: "Lumino",
		source: "Shop - Trial Rank 38",
		nocturnalEchoMaterial: "Ring of Chronal Reversion",
		skillUpgradeMaterials: {
			t1: "Veil of Silence",
			t2: "Eye of Infinity",
			t3: "Crown of Enlightenment",
		},
		imagecode: "Nifu",
	},
	{
		name: "Tabethe",
		rank: "A",
		id: 11,
		element: "Hydro",
		source: "Shop",
		nocturnalEchoMaterial: "Ring of Escaped Entropy",
		skillUpgradeMaterials: {
			t1: "Gleaming Arrow",
			t2: "Gleaming Precision Scope",
			t3: "Gleaming Quiver",
		},
		imagecode: "Zhangyu",
	},
	{
		name: "Yale and Oliver",
		rank: "A",
		id: 12,
		element: "Pyro",
		source: "Nocturnal Echoes",
		nocturnalEchoMaterial: "Ring of Chronal Reversion",
		skillUpgradeMaterials: {
			t1: "Gleaming Arrow",
			t2: "Gleaming Precision Scope",
			t3: "Gleaming Quiver",
		},
		imagecode: "Yeer",
	},
	{
		name: "Truffle and Filbert",
		rank: "B",
		id: 13,
		element: "Anemo",
		source: "Story / Nocturnal Echoes",
		nocturnalEchoMaterial: "Ring of Justice Rekindled",
		skillUpgradeMaterials: {
			t1: "Herbal Sprig",
			t2: "Processed Herb",
			t3: "Compound Potion",
		},
		imagecode: "Songlu",
	},
	{
		name: "Rhythm",
		rank: "A",
		id: 14,
		element: "Electro",
		source: "Shop",
		nocturnalEchoMaterial: "Ring of Justice Rekindled",
		skillUpgradeMaterials: {
			t1: "Veil of Silence",
			t2: "Eye of Infinity",
			t3: "Crown of Enlightenment",
		},
		imagecode: "Lise",
	},
	{
		name: "Hellfire",
		rank: "A",
		id: 15,
		element: "Pyro",
		source: "Nocturnal Echoes",
		nocturnalEchoMaterial: "Ring of Escaped Entropy",
		skillUpgradeMaterials: {
			t1: "Iron Emblem",
			t2: "Silver Emblem",
			t3: "Gilded Emblem",
		},
		imagecode: "Haier",
	},
	{
		name: "Lisbell",
		rank: "A",
		id: 16,
		element: "Lumino",
		source: "Shop / Mystic Maze",
		nocturnalEchoMaterial: "Ring of Chronal Reversion",
		skillUpgradeMaterials: {
			t1: "Iron Emblem",
			t2: "Silver Emblem",
			t3: "Gilded Emblem",
		},
		consonanceWeapon: "Greatsword",
		imagecode: "Baonu",
	},
	{
		name: "Phantasio",
		rank: "B",
		id: 17,
		element: "Umbro",
		source: "Nocturnal Echoes",
		nocturnalEchoMaterial: "Ring of Severed Fear",
		skillUpgradeMaterials: {
			t1: "Iron Emblem",
			t2: "Silver Emblem",
			t3: "Gilded Emblem",
		},
		imagecode: "Tuosi",
	},
	{
		name: "Psyche",
		rank: "B",
		id: 18,
		element: "Anemo",
		source: "Nocturnal Echoes",
		nocturnalEchoMaterial: "Ring of Chronal Reversion",
		skillUpgradeMaterials: {
			t1: "Gleaming Arrow",
			t2: "Gleaming Precision Scope",
			t3: "Gleaming Quiver",
		},
		consonanceWeapon: "Assault Rifle",
		imagecode: "Saiqi",
	},
	{
		name: "Fina",
		rank: "B",
		id: 19,
		element: "Lumino",
		source: "Nocturnal Echoes",
		nocturnalEchoMaterial: "Ring of Escaped Entropy",
		skillUpgradeMaterials: {
			t1: "Herbal Sprig",
			t2: "Processed Herb",
			t3: "Compound Potion",
		},
		imagecode: "Feina",
	},
	{
		name: "Fushu",
		rank: "B",
		id: 20,
		element: "Hydro",
		source: "Nocturnal Echoes",
		nocturnalEchoMaterial: "Ring of Chronal Reversion",
		skillUpgradeMaterials: {
			t1: "Herbal Sprig",
			t2: "Processed Herb",
			t3: "Compound Potion",
		},
		imagecode: "Baiheng",
	},
	{
		name: "Kezhou",
		rank: "B",
		id: 21,
		element: "Lumino",
		source: "Immersive Theater",
		nocturnalEchoMaterial: "Ring of Chronal Reversion",
		skillUpgradeMaterials: {
			t1: "Iron Emblem",
			t2: "Silver Emblem",
			t3: "Gilded Emblem",
		},
		imagecode: "Kezhou",
	},
];

export const elementUpgradeMaterials: ElementUpgradeMaterials[] = [
	{
		element: "Hydro",
		ascensionMaterials: {
			t1: "Azure Pearl",
			t2: "Humectant",
			t3: "Water Purifier",
		},
		forgingMaterials: {
			t1: "Stone Powder",
			t2: "Insulation Coating",
			t3: "Filthoid Tentacle",
			t4: "Filthoid Polymer",
		},
	},
	{
		element: "Pyro",
		ascensionMaterials: {
			t1: "Flame Lizard Scale",
			t2: "Everbright Flame",
			t3: "Fire-Tempered Shackles",
		},
		forgingMaterials: {
			t1: "Damaged Sal Volatile",
			t2: "Fuel Reagent",
			t3: "Sacred Candle",
			t4: "Serum Syringe",
		},
	},
	{
		element: "Anemo",
		ascensionMaterials: {
			t1: "Withered Bough",
			t2: "Galeweaver",
			t3: "Oceanifly",
		},
		forgingMaterials: {
			t1: "Vermillion Teardrop",
			t2: "Snowswift Tail Feather",
			t3: "Sacred Candle",
			t4: "Serum Syringe",
		},
	},
	{
		element: "Electro",
		ascensionMaterials: {
			t1: "Lightning Rod",
			t2: "Stormfall Jade",
			t3: "Golden Wool",
		},
		forgingMaterials: {
			t1: "Chain",
			t2: "Vehicle Armour",
			t3: "Sacred Candle",
			t4: "Serum Syringe",
		},
	},
	{
		element: "Lumino",
		ascensionMaterials: {
			t1: "Lense of Enlightenment",
			t2: "Golden Floriated Diadem",
			t3: "Copy of Elysian Hymnal",
		},
		forgingMaterials: {
			t1: "Filthoid Clot",
			t2: "Statue Debris",
			t3: "Filthoid Tentacle",
			t4: "Filthoid Polymer",
		},
	},
	{
		element: "Umbro",
		ascensionMaterials: {
			t1: "Rust-Etched Dagger",
			t2: "Obsidian Key",
			t3: "Tome of Noclunism Ritual",
		},
		forgingMaterials: {
			t1: "Filthoid Clot",
			t2: "Statue Debris",
			t3: "Filthoid Tentacle",
			t4: "Filthoid Polymer",
		},
	},
];

export const defaultCharacterUpgrade: CharacterUpgradeConfig = {
	name: "",
	level: {
		start: "1",
		end: "80",
	},
	type: "Character",
	skill: {
		current: 1,
		target: 1,
		node1: {
			isUnlocked: false,
		},
		node2: {
			isUnlocked: false,
		},
	},
	ult: {
		current: 1,
		target: 1,
		node1: {
			isUnlocked: false,
		},
		node2: {
			isUnlocked: false,
		},
	},
	passive: {
		current: 1,
		target: 1,
		node1: {
			isUnlocked: false,
		},
		node2: {
			isUnlocked: false,
		},
	},
};
