import type { WeaponLevelingMaterial } from "../types/ascention";
import type { Weapon } from "../types/weapon";
import type { WeaponUpgradeMaterials } from "../types/weaponUpgrades";

export const weapons: Weapon[] = [
  {
    id: 1,
    name: "Flamme De Epuration",
    weaponType: "Assault Rifle",
    range: "Ranged",
    source: "Shop - Trial Rank 8",
  },
  {
    id: 2,
    name: "Withershade",
    weaponType: "Katana",
    range: "Melee",
    source: "Shop - Trial Rank 10",
  },
  {
    id: 3,
    name: "Searing Sandwhisper",
    weaponType: "Bow",
    range: "Ranged",
    source: "Shop - Trial Rank 12",
  },
  {
    id: 4,
    name: "Blade Amberglow",
    weaponType: "Sword",
    range: "Melee",
    source: "Shop - Trial Rank 16",
  },
  {
    id: 5,
    name: "Undying Oneiros",
    weaponType: "Whipsword",
    range: "Melee",
    source: "Shop - Trial Rank 17",
  },
  {
    id: 6,
    name: "Rendhusk",
    weaponType: "Pistol",
    range: "Ranged",
    source: "Shop - Trial Rank 19",
  },
  {
    id: 7,
    name: "Silverwhite Edict",
    weaponType: "Grenade Launcher",
    range: "Ranged",
    source: "Shop - Trial Rank 22",
  },
  {
    id: 8,
    name: "Siren's Kiss",
    weaponType: "Polearm",
    range: "Melee",
    source: "Shop - Trial Rank 23",
  },
  {
    id: 9,
    name: "Exiled Fangs",
    weaponType: "Dual Blades",
    range: "Melee",
    source: "Shop - Trial Rank 24",
  },
  {
    id: 10,
    name: "Destructo",
    weaponType: "Grenade Launcher",
    range: "Ranged",
    source: "Shop - Trial Rank 27",
  },
  {
    id: 11,
    name: "Remanent Reminiscence",
    weaponType: "Sword",
    range: "Melee",
    source: "Shop - Trial Rank 28",
  },
  {
    id: 12,
    name: "Wanewraith",
    weaponType: "Polearm",
    range: "Melee",
    source: "Shop - Trial Rank 30",
  },
  {
    id: 13,
    name: "Ironforger",
    weaponType: "Greatsword",
    range: "Melee",
    source: "Shop - Trial Rank 32",
  },
  {
    id: 14,
    name: "Ingenious Tactics",
    weaponType: "Sword",
    range: "Melee",
    source: "Shop - Trial Rank 37",
  },
  {
    id: 15,
    name: "Entropic Singularity",
    weaponType: "Pistol",
    range: "Ranged",
    source: "Shop - Trial Rank 39",
  },
  {
    id: 16,
    name: "Pyrothirst",
    weaponType: "Greatsword",
    range: "Melee",
    source: "Shop - Trial Rank 40",
  },
  {
    id: 17,
    name: "Momiji Itteki",
    weaponType: "Katana",
    range: "Melee",
    source: "Shop - Trial Rank 42",
  },
  {
    id: 18,
    name: "Bluecurrent Pulse",
    weaponType: "Dual Pistols",
    range: "Ranged",
    source: "Shop - Trial Rank 43",
  },
  {
    id: 19,
    name: "Osteobreaker",
    weaponType: "Assault Rifle",
    range: "Ranged",
    source: "Shop - Trial Rank 48",
  },
  {
    id: 20,
    name: "Tetherlash",
    weaponType: "Whipsword",
    range: "Melee",
    source: "Shop - Trial Rank 51",
  },
  {
    id: 21,
    name: "Excresduo",
    weaponType: "Dual Pistols",
    range: "Ranged",
    source: "Shop - Trial Rank 51",
  },
  {
    id: 22,
    name: "Silent Sower",
    weaponType: "Shotgun",
    range: "Ranged",
    source: "Shop - Trial Rank 53",
  },
  {
    id: 23,
    name: "Fathomless Sharkgaze",
    weaponType: "Dual Blades",
    range: "Melee",
    source: "Shop - Trial Rank 57",
  },
  {
    id: 24,
    name: "Screamshot",
    weaponType: "Shotgun",
    range: "Ranged",
    source: "Shop - Trial Rank 59",
  },
  {
    id: 25,
    name: "Soulrend",
    weaponType: "Bow",
    range: "Ranged",
    source: "Shop - Trial Rank 62",
  },
  {
    id: 26,
    name: "Shackle of Lonewolf",
    weaponType: "Sword",
    range: "Melee",
    source: "Shop",
  },
  {
    id: 27,
    name: "Sacrosanct Chorus",
    weaponType: "Dual Pistols",
    range: "Ranged",
    source: "Nocturnal Echoes",
  },
  {
    id: 28,
    name: "Stellar Finality",
    weaponType: "Grenade Launcher",
    range: "Ranged",
    source: "Nocturnal Echoes",
  },
  {
    id: 29,
    name: "Blast Artistry",
    weaponType: "Shotgun",
    range: "Ranged",
    source: "Nocturnal Echoes",
  },
  {
    id: 30,
    name: "Vernal Jade Halberd",
    weaponType: "Polearm",
    range: "Melee",
    source: "Shop",
  },
  {
    id: 31,
    name: "Viridis Reefs",
    weaponType: "Whipsword",
    range: "Melee",
    source: "Nocturnal Echoes",
  },
  {
    id: 32,
    name: "Guixu Ratchet",
    weaponType: "Grenade Launcher",
    range: "Ranged",
    source: "Nocturnal Echoes",
  },
  {
    id: 33,
    name: "Wandering Rose",
    weaponType: "Sword",
    range: "Melee",
    source: "Nocturnal Echoes",
  },
  {
    id: 34,
    name: "Sacrosanct Decree",
    weaponType: "Pistol",
    range: "Ranged",
    source: "Nocturnal Echoes",
  },
  {
    id: 35,
    name: "Exiled Thunderwyrm",
    weaponType: "Assault Rifle",
    range: "Ranged",
    source: "Shop",
  },
  {
    id: 36,
    name: "Submerged Serenade",
    weaponType: "Assault Rifle",
    range: "Ranged",
    source: "Shop",
  },
  {
    id: 37,
    name: "Punitive Inferno",
    weaponType: "Greatsword",
    range: "Melee",
    source: "Nocturnal Echoes",
  },
  {
    id: 38,
    name: "Day of Sacred Verdict",
    weaponType: "Shotgun",
    range: "Ranged",
    source: "Nocturnal Echoes",
  },
  {
    id: 39,
    name: "Embla Inflorescence",
    weaponType: "Bow",
    range: "Ranged",
    source: "Shop",
  },
  {
    id: 40,
    name: "Arclight Apocalypses",
    weaponType: "Bow",
    range: "Ranged",
    source: "Nocturnal Echoes",
  },
  {
    id: 41,
    name: "Sacred Favour",
    weaponType: "Katana",
    range: "Melee",
    source: "Nocturnal Echoes",
  },
  {
    id: 42,
    name: "Aureate Yore",
    weaponType: "Dual Blades",
    range: "Melee",
    source: "Nocturnal Echoes",
  },
  {
    id: 43,
    name: "Daybreak Hymn",
    weaponType: "Assault Rifle",
    range: "Ranged",
    source: "Nocturnal Echoes",
  },
  {
    id: 44,
    name: "Elpides Abound",
    weaponType: "Polearm",
    range: "Melee",
    source: "Nocturnal Echoes",
  },
  {
    id: 45,
    name: "Dreamweaver's Feather",
    weaponType: "Assault Rifle",
    range: "Ranged",
    source: "Nocturnal Echoes",
  },
  {
    id: 46,
    name: "Halcyon Gracefall",
    weaponType: "Whipsword",
    range: "Melee",
    source: "Nocturnal Echoes",
  },
  {
    id: 47,
    name: "Cloudveil Unfurl",
    weaponType: "Assault Rifle",
    range: "Ranged",
    source: "Nocturnal Echoes",
  },
  {
    id: 48,
    name: "Ephemeral Lumina",
    weaponType: "Assault Rifle",
    range: "Ranged",
    source: "Immersive Theater",
  },
  {
    id: 49,
    name: "Dove of Tomorrow",
    weaponType: "Polearm",
    range: "Melee",
    source: "Nocturnal Echoes",
  },
];

export const weaponLevelingMaterials: WeaponLevelingMaterial[] = [
  {
    level: "1",
    exp: 0,
    coins: { default: 0 },
    forgingMaterials: { T1_Green: 0, T2_Blue: 0 },
    ascensionMaterials: {
      primary: { T1_Green: 0, T2_Blue: 0, T3_Purple: 0 },
      secondary: { T1_Green: 0, T2_Blue: 0, T3_Purple: 0 },
    },
  },
  {
    level: "20",
    exp: 33,
    coins: { default: 3300 },
    forgingMaterials: { T1_Green: 0, T2_Blue: 0 },
    ascensionMaterials: {
      primary: { T1_Green: 0, T2_Blue: 0, T3_Purple: 0 },
      secondary: { T1_Green: 0, T2_Blue: 0, T3_Purple: 0 },
    },
  },
  {
    level: "20,1",
    exp: 33,
    coins: { default: 6100 },
    forgingMaterials: { T1_Green: 6, T2_Blue: 0 },
    ascensionMaterials: {
      primary: { T1_Green: 2, T2_Blue: 0, T3_Purple: 0 },
      secondary: { T1_Green: 0, T2_Blue: 0, T3_Purple: 0 },
    },
  },
  {
    level: "30",
    exp: 88,
    coins: { default: 11600 },
    forgingMaterials: { T1_Green: 6, T2_Blue: 0 },
    ascensionMaterials: {
      primary: { T1_Green: 2, T2_Blue: 0, T3_Purple: 0 },
      secondary: { T1_Green: 0, T2_Blue: 0, T3_Purple: 0 },
    },
  },
  {
    level: "30,1",
    exp: 88,
    coins: { default: 17700 },
    forgingMaterials: { T1_Green: 6, T2_Blue: 3 },
    ascensionMaterials: {
      primary: { T1_Green: 6, T2_Blue: 0, T3_Purple: 0 },
      secondary: { T1_Green: 2, T2_Blue: 0, T3_Purple: 0 },
    },
  },
  {
    level: "40",
    exp: 168,
    coins: { default: 25700 },
    forgingMaterials: { T1_Green: 6, T2_Blue: 3 },
    ascensionMaterials: {
      primary: { T1_Green: 6, T2_Blue: 0, T3_Purple: 0 },
      secondary: { T1_Green: 2, T2_Blue: 0, T3_Purple: 0 },
    },
  },
  {
    level: "40,1",
    exp: 168,
    coins: { default: 32600 },
    forgingMaterials: { T1_Green: 6, T2_Blue: 9 },
    ascensionMaterials: {
      primary: { T1_Green: 6, T2_Blue: 3, T3_Purple: 0 },
      secondary: { T1_Green: 2, T2_Blue: 1, T3_Purple: 0 },
    },
  },
  {
    level: "50",
    exp: 305,
    coins: { default: 46300 },
    forgingMaterials: { T1_Green: 6, T2_Blue: 9 },
    ascensionMaterials: {
      primary: { T1_Green: 6, T2_Blue: 3, T3_Purple: 0 },
      secondary: { T1_Green: 2, T2_Blue: 1, T3_Purple: 0 },
    },
  },
  {
    level: "50,1",
    exp: 305,
    coins: { default: 63300 },
    forgingMaterials: { T1_Green: 6, T2_Blue: 21 },
    ascensionMaterials: {
      primary: { T1_Green: 6, T2_Blue: 3, T3_Purple: 6 },
      secondary: { T1_Green: 2, T2_Blue: 1, T3_Purple: 2 },
    },
  },
  {
    level: "60",
    exp: 508,
    coins: { default: 83600 },
    forgingMaterials: { T1_Green: 6, T2_Blue: 21 },
    ascensionMaterials: {
      primary: { T1_Green: 6, T2_Blue: 3, T3_Purple: 6 },
      secondary: { T1_Green: 2, T2_Blue: 1, T3_Purple: 2 },
    },
  },
  {
    level: "60,1",
    exp: 508,
    coins: { default: 132600 },
    forgingMaterials: { T1_Green: 6, T2_Blue: 45 },
    ascensionMaterials: {
      primary: { T1_Green: 6, T2_Blue: 3, T3_Purple: 16 },
      secondary: { T1_Green: 2, T2_Blue: 1, T3_Purple: 6 },
    },
  },
  {
    level: "70",
    exp: 812,
    coins: { default: 163000 },
    forgingMaterials: { T1_Green: 6, T2_Blue: 45 },
    ascensionMaterials: {
      primary: { T1_Green: 6, T2_Blue: 3, T3_Purple: 16 },
      secondary: { T1_Green: 2, T2_Blue: 1, T3_Purple: 6 },
    },
  },
  {
    level: "70,1",
    exp: 812,
    coins: { default: 343000 },
    forgingMaterials: { T1_Green: 6, T2_Blue: 93 },
    ascensionMaterials: {
      primary: { T1_Green: 6, T2_Blue: 3, T3_Purple: 36 },
      secondary: { T1_Green: 2, T2_Blue: 1, T3_Purple: 14 },
    },
  },
  {
    level: "80",
    exp: 1438,
    coins: { default: 405600 },
    forgingMaterials: { T1_Green: 6, T2_Blue: 93 },
    ascensionMaterials: {
      primary: { T1_Green: 6, T2_Blue: 3, T3_Purple: 36 },
      secondary: { T1_Green: 2, T2_Blue: 1, T3_Purple: 14 },
    },
  },
  {
    level: "80,1",
    exp: 1438,
    coins: { default: 405600 },
    forgingMaterials: { T1_Green: 6, T2_Blue: 93 },
    ascensionMaterials: {
      primary: { T1_Green: 6, T2_Blue: 3, T3_Purple: 36 },
      secondary: { T1_Green: 2, T2_Blue: 1, T3_Purple: 14 },
    },
  },
];

export const weaponUpgradeMaterials: WeaponUpgradeMaterials[] = [
  {
    weaponType: "Greatsword",
    forgingMaterials: { t1: "Filthoid Clot", t2: "Statue Debris" },
    ascensionMaterials: { primary: "Grip", secondary: "Decoration" },
  },
  {
    weaponType: "Dual Blades",
    forgingMaterials: { t1: "Vermillion Teardrop", t2: "Chain" },
    ascensionMaterials: { primary: "Blade", secondary: "Decoration" },
  },
  {
    weaponType: "Katana",
    forgingMaterials: { t1: "Vermillion Teardrop", t2: "Chain" },
    ascensionMaterials: { primary: "Blade", secondary: "Decoration" },
  },
  {
    weaponType: "Polearm",
    forgingMaterials: { t1: "Stone Powder", t2: "Insulation Coating" },
    ascensionMaterials: { primary: "Grip", secondary: "Blade" },
  },
  {
    weaponType: "Sword",
    forgingMaterials: { t1: "Damaged Sal Volatile", t2: "Fuel Reagent" },
    ascensionMaterials: { primary: "Grip", secondary: "Blade" },
  },
  {
    weaponType: "Whipsword",
    forgingMaterials: { t1: "Damaged Sal Volatile", t2: "Fuel Reagent" },
    ascensionMaterials: { primary: "Grip", secondary: "Blade" },
  },
  {
    weaponType: "Bow",
    forgingMaterials: { t1: "Vermillion Teardrop", t2: "Chain" },
    ascensionMaterials: { primary: "Frame", secondary: "Barrel" },
  },
  {
    weaponType: "Grenade Launcher",
    forgingMaterials: { t1: "Vermillion Teardrop", t2: "Chain" },
    ascensionMaterials: { primary: "Frame", secondary: "Bolt" },
  },
  {
    weaponType: "Dual Pistols",
    forgingMaterials: { t1: "Vermillion Teardrop", t2: "Chain" },
    ascensionMaterials: { primary: "Barrel", secondary: "Frame" },
  },
  {
    weaponType: "Assault Rifle",
    forgingMaterials: { t1: "Vermillion Teardrop", t2: "Chain" },
    ascensionMaterials: { primary: "Bolt", secondary: "Frame" },
  },
  {
    weaponType: "Pistol",
    forgingMaterials: { t1: "Vermillion Teardrop", t2: "Chain" },
    ascensionMaterials: { primary: "Barrel", secondary: "Frame" },
  },
  {
    weaponType: "Shotgun",
    forgingMaterials: { t1: "Vermillion Teardrop", t2: "Chain" },
    ascensionMaterials: { primary: "Barrel", secondary: "Frame" },
  },
];